name: FarmerPouch
version: 1.0.0
main: com.mrhistories.farmerpouch.FarmerPouchPlugin
api-version: "1.20"
author: MrHistories

softdepend:
  - WorldGuard

commands:
  pouch:
    description: Farmer Pouch ana komutu
    usage: /pouch

  coinmarket:
    description: TarımCoin marketini açar
    usage: /coinmarket

  tarimcoin:
    description: TarımCoin komutu
    usage: /tarimcoin

permissions:
  farmerpouch.admin:
    default: op
  tarimcoin.admin:
    default: op
